# Generated by Django 4.2.1 on 2023-06-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
